/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.5
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.eve.api;

import io.swagger.client.eve.ApiException;
import io.swagger.client.eve.model.Forbidden;
import io.swagger.client.eve.model.GetCharactersCharacterIdKillmailsRecent200Ok;
import io.swagger.client.eve.model.GetCorporationsCorporationIdKillmailsRecent200Ok;
import io.swagger.client.eve.model.GetKillmailsKillmailIdKillmailHashOk;
import io.swagger.client.eve.model.GetKillmailsKillmailIdKillmailHashUnprocessableEntity;
import io.swagger.client.eve.model.InternalServerError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for KillmailsApi
 */
@Ignore
public class KillmailsApiTest {

    private final KillmailsApi api = new KillmailsApi();

    
    /**
     * Get character kills and losses
     *
     * Return a list of character&#39;s recent kills and losses  ---  This route is cached for up to 120 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCharactersCharacterIdKillmailsRecentTest() throws ApiException {
        Integer characterId = null;
        String datasource = null;
        Integer maxCount = null;
        Integer maxKillId = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCharactersCharacterIdKillmailsRecent200Ok> response = api.getCharactersCharacterIdKillmailsRecent(characterId, datasource, maxCount, maxKillId, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get corporation kills and losses
     *
     * Get a list of corporation&#39;s recent kills and losses  ---  This route is cached for up to 300 seconds  --- Requires one of the following EVE corporation role(s): Director
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCorporationsCorporationIdKillmailsRecentTest() throws ApiException {
        Integer corporationId = null;
        String datasource = null;
        Integer maxKillId = null;
        String token = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetCorporationsCorporationIdKillmailsRecent200Ok> response = api.getCorporationsCorporationIdKillmailsRecent(corporationId, datasource, maxKillId, token, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get a single killmail
     *
     * Return a single killmail from its ID and hash  ---  This route is cached for up to 1209600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getKillmailsKillmailIdKillmailHashTest() throws ApiException {
        String killmailHash = null;
        Integer killmailId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetKillmailsKillmailIdKillmailHashOk response = api.getKillmailsKillmailIdKillmailHash(killmailHash, killmailId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
