/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.eve.api;

import io.swagger.client.eve.ApiException;
import io.swagger.client.eve.model.GetWarsWarIdKillmails200Ok;
import io.swagger.client.eve.model.GetWarsWarIdKillmailsUnprocessableEntity;
import io.swagger.client.eve.model.GetWarsWarIdOk;
import io.swagger.client.eve.model.GetWarsWarIdUnprocessableEntity;
import io.swagger.client.eve.model.InternalServerError;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for WarsApi
 */
@Ignore
public class WarsApiTest {

    private final WarsApi api = new WarsApi();

    
    /**
     * List wars
     *
     * Return a list of wars  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWarsTest() throws ApiException {
        String datasource = null;
        Integer maxWarId = null;
        String userAgent = null;
        String xUserAgent = null;
        List<Integer> response = api.getWars(datasource, maxWarId, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * Get war information
     *
     * Return details about a war  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWarsWarIdTest() throws ApiException {
        Integer warId = null;
        String datasource = null;
        String userAgent = null;
        String xUserAgent = null;
        GetWarsWarIdOk response = api.getWarsWarId(warId, datasource, userAgent, xUserAgent);

        // TODO: test validations
    }
    
    /**
     * List kills for a war
     *
     * Return a list of kills related to a war  ---  This route is cached for up to 3600 seconds
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWarsWarIdKillmailsTest() throws ApiException {
        Integer warId = null;
        String datasource = null;
        Integer page = null;
        String userAgent = null;
        String xUserAgent = null;
        List<GetWarsWarIdKillmails200Ok> response = api.getWarsWarIdKillmails(warId, datasource, page, userAgent, xUserAgent);

        // TODO: test validations
    }
    
}
