/*
 * EVE Swagger Interface
 * An OpenAPI for EVE Online
 *
 * OpenAPI spec version: 0.7.6
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.eve.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.eve.model.GetFleetsFleetIdWingsSquad;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * 200 ok object
 */
@ApiModel(description = "200 ok object")

public class GetFleetsFleetIdWings200Ok {
  @SerializedName("name")
  private String name = null;

  @SerializedName("id")
  private Long id = null;

  @SerializedName("squads")
  private List<GetFleetsFleetIdWingsSquad> squads = new ArrayList<GetFleetsFleetIdWingsSquad>();

  public GetFleetsFleetIdWings200Ok name(String name) {
    this.name = name;
    return this;
  }

   /**
   * name string
   * @return name
  **/
  @ApiModelProperty(required = true, value = "name string")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public GetFleetsFleetIdWings200Ok id(Long id) {
    this.id = id;
    return this;
  }

   /**
   * id integer
   * @return id
  **/
  @ApiModelProperty(required = true, value = "id integer")
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  public GetFleetsFleetIdWings200Ok squads(List<GetFleetsFleetIdWingsSquad> squads) {
    this.squads = squads;
    return this;
  }

  public GetFleetsFleetIdWings200Ok addSquadsItem(GetFleetsFleetIdWingsSquad squadsItem) {
    this.squads.add(squadsItem);
    return this;
  }

   /**
   * squads array
   * @return squads
  **/
  @ApiModelProperty(required = true, value = "squads array")
  public List<GetFleetsFleetIdWingsSquad> getSquads() {
    return squads;
  }

  public void setSquads(List<GetFleetsFleetIdWingsSquad> squads) {
    this.squads = squads;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetFleetsFleetIdWings200Ok getFleetsFleetIdWings200Ok = (GetFleetsFleetIdWings200Ok) o;
    return Objects.equals(this.name, getFleetsFleetIdWings200Ok.name) &&
        Objects.equals(this.id, getFleetsFleetIdWings200Ok.id) &&
        Objects.equals(this.squads, getFleetsFleetIdWings200Ok.squads);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, id, squads);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetFleetsFleetIdWings200Ok {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    squads: ").append(toIndentedString(squads)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

